# Use the apt provider instead of the default Nix provider
[providers]
apt = true

# Install packages using apt
[phases.setup]
aptPkgs = ["ffmpeg", "ffmpeg-doc", "libavcodec-extra"]

# Set environment variables
[phases.setup.env]
PATH = "/usr/bin:$PATH"