[phases.setup]
aptPkgs = ["ffmpeg", "ffmpeg-doc", "libavcodec-extra"]

[phases.setup.env]
PATH = "/usr/bin:$PATH"
LD_LIBRARY_PATH = "/usr/lib:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
FFMPEG_PATH = "/usr/bin/ffmpeg"
FFPROBE_PATH = "/usr/bin/ffprobe"