# Providers should be an array, not a map
[build]
providers = ["apt"]

# Install packages using apt
[phases.setup]
aptPkgs = ["ffmpeg", "ffmpeg-doc", "libavcodec-extra"]

# Set environment variables
[phases.setup.env]
PATH = "/usr/bin:$PATH"